// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Travel Walter API",
        "description": "API para gerenciar viagens e despesas",
        "version": "1.0.0",
        "contact": {
            "name": "Luiz Felipe Oliveira",
            "email": "luizfelipeeoliveiraac@gmail.com"
        }
    },
    "host": "localhost:8080",
    "basePath": "/",
    "schemes": ["http"],
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "paths": {
        "/health": {
            "get": {
                "summary": "Health check",
                "operationId": "health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "summary": "Registrar novo usuário",
                "operationId": "register",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string", "example": "João Silva"},
                                "email": {"type": "string", "example": "joao@example.com"},
                                "password": {"type": "string", "example": "senha123"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário criado com sucesso"
                    },
                    "400": {
                        "description": "Erro de validação"
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "summary": "Fazer login",
                "operationId": "login",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {"type": "string"},
                                "password": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login bem-sucedido"
                    },
                    "401": {
                        "description": "Credenciais inválidas"
                    }
                }
            }
        },
        "/auth/profile": {
            "get": {
                "summary": "Obter perfil do usuário",
                "operationId": "getProfile",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {
                        "description": "Perfil do usuário"
                    },
                    "401": {
                        "description": "Não autenticado"
                    }
                }
            }
        },
        "/travels": {
            "get": {
                "summary": "Listar viagens",
                "operationId": "listTravels",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {
                        "description": "Lista de viagens"
                    }
                }
            },
            "post": {
                "summary": "Criar nova viagem",
                "operationId": "createTravel",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "destino": {"type": "string"},
                                "data_inicio": {"type": "string", "example": "2024-08-10"},
                                "data_fim": {"type": "string", "example": "2024-08-15"},
                                "descricao": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Viagem criada"
                    }
                }
            }
        },
        "/travels/{id}": {
            "get": {
                "summary": "Obter detalhes de uma viagem",
                "operationId": "getTravel",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalhes da viagem"
                    }
                }
            },
            "put": {
                "summary": "Atualizar viagem",
                "operationId": "updateTravel",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Viagem atualizada"
                    }
                }
            },
            "delete": {
                "summary": "Deletar viagem",
                "operationId": "deleteTravel",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Viagem deletada"
                    }
                }
            }
        },
        "/expenses/{travel_id}": {
            "get": {
                "summary": "Listar gastos de uma viagem",
                "operationId": "listExpenses",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "travel_id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de gastos"
                    }
                }
            },
            "post": {
                "summary": "Criar novo gasto",
                "operationId": "createExpense",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "travel_id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "descricao": {"type": "string"},
                                "valor": {"type": "number"},
                                "categoria": {"type": "string"},
                                "data_gasto": {"type": "string", "example": "2024-08-10"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Gasto criado"
                    }
                }
            }
        },
        "/expenses/{travel_id}/total": {
            "get": {
                "summary": "Obter total de gastos de uma viagem",
                "operationId": "getTravelTotal",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "travel_id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Total de gastos"
                    }
                }
            }
        },
        "/expenses/{travel_id}/{id}": {
            "get": {
                "summary": "Obter detalhes de um gasto",
                "operationId": "getExpense",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "travel_id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalhes do gasto"
                    }
                }
            },
            "put": {
                "summary": "Atualizar gasto",
                "operationId": "updateExpense",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "travel_id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Gasto atualizado"
                    }
                }
            },
            "delete": {
                "summary": "Deletar gasto",
                "operationId": "deleteExpense",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "name": "travel_id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Gasto deletado"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
} = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{
	Version:     "1.0.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{"http"},
	Title:       "Travel Walter API",
	Description: "API para gerenciar viagens e despesas",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

func init() {
	swag.Register(swag.Name, &s{})
}
